### ISSUE TITLE
HarmCategory

### ISSUE THREAD

**Issue by hongjinjo** [jzou19957/Automatic_OCR_Through_Gemni_Vision#1]
Hi I am trying to use your code for OCR, but face the following issue.

Traceback (most recent call last):
  File ".../Gemini_OCR/Gemni_vision_for_OCR.py", line 27, in <module>
    from google.generativeai.types import HarmCategory, HarmBlockThreshold
ImportError: cannot import name 'HarmCategory' from 'google.generativeai.types'

**Comment by cwittern** [comment]
It looks like your python is too old.  I had the same error with Python 3.7.5, but after upgrading to 3.11.4 the error went away.
